version: '2'
services:
  grades-db:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: grades
      MYSQL_HOST: grades_db
  grades-ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4002 -b '0.0.0.0'"
    ports:
      - "4002:4002"
    depends_on:
      - grades-db
